model_provider = "crs"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
disable_response_storage = true
preferred_auth_method = "sk-rcPmngVUVygvNHWhvz4r4YdRsacWTY9gv0DipFmTRis4xLAv"


sandbox_mode = "danger-full-access"
[model_providers]
[model_providers.crs]
name = "crs"
base_url = "https://api2.apiaqi.com/v1"
wire_api = "responses"

[notice]
hide_full_access_warning = true
