import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { createApp } from '../src/app.js'

function parseSseEvents(body) {
  return String(body || '')
    .trim()
    .split('\n\n')
    .filter(Boolean)
    .map((chunk) => {
      const lines = chunk.split('\n')
      const event = lines.find((line) => line.startsWith('event:'))?.replace('event:', '').trim()
      const dataLine = lines.find((line) => line.startsWith('data:'))?.replace('data:', '').trim()
      return {
        event,
        data: dataLine ? JSON.parse(dataLine) : null
      }
    })
}

test('queries actual audit events generated by a live analysis request', async () => {
  const app = await createApp({
    baseDir: await mkdtemp(path.join(tmpdir(), 'v2-ops-audit-'))
  })

  try {
    const analysisResponse = await app.inject({
      method: 'POST',
      url: '/api/v2/analysis',
      headers: {
        'x-tenant-id': 'tenant-001',
        'x-user-id': 'user-001'
      },
      payload: {
        session_id: 'session-audit',
        query: 'Give me a 30s briefing of this area.',
        viewport: {
          zoom: 15,
          bbox: [114.30, 30.52, 114.36, 30.57]
        }
      }
    })

    const events = parseSseEvents(analysisResponse.body)
    const fastResult = events.find((entry) => entry.event === 'fast.result')
    assert.ok(fastResult?.data?.job_id)

    const auditResponse = await app.inject({
      method: 'GET',
      url: `/api/v2/ops/audit-events?job_id=${fastResult.data.job_id}`
    })

    assert.equal(auditResponse.statusCode, 200)
    const payload = auditResponse.json()
    assert.equal(payload.schema_version, 'contract.v2.0')
    assert.equal(Array.isArray(payload.items), true)
    assert.equal(payload.items.some((entry) => entry.event === 'fast.result'), true)
    assert.equal(payload.items.some((entry) => entry.session_id === 'session-audit'), true)
  } finally {
    await app.close()
  }
})
